# author: GALLITELLI Davide
# project: SR2I 203 - Botnet Mirai : Simulation et mise en oeuvre
# MIRAI COMPOSER
version: '2'

services:
    # COMPILE ALL THE FILES IN THE MIRAI SOLUTION
    # compiler:
    #     container_name: "mirai_compiler"
    #     build: ./Dockerfile-Compiler

    # CNC CONFIGURATION
    cnc:
        container_name: "mirai_cnc"
        hostname: cnc
        domainname: mirai.com
        build:
            context: .
            dockerfile: ./Dockerfile-CNC
        networks:
            vpcbr:
                ipv4_address: 172.25.0.2

    # SCANLISTEN CONFIGURATION
    scanlisten:
        container_name: "mirai_scan"
        hostname: scan
        domainname: mirai.com
        build:
            context: .
            dockerfile: ./Dockerfile-SCAN
        links:
            - cnc
        networks:
            vpcbr:
                ipv4_address: 172.25.0.3

    # LOADER CONFIGURATION
    loader:
        container_name: "mirai_loader"
        hostname: loader
        domainname: mirai.com
        build:
            context: .
            dockerfile: ./Dockerfile-LOAD
        links:
            - cnc
        networks:
            vpcbr:
                ipv4_address: 172.25.0.4
        dns:
            - bind

    # BOT CONFIGURATION
    bot:
        container_name: "mirai_bot"
        hostname: bot
        domainname: mirai.com
        build:
            context: .
            dockerfile: ./Dockerfile-BOT
        depends_on:
            - cnc
            - loader
            - scanlisten
        links:
            - cnc
            - loader
            - bind
        networks:
            vpcbr:
                ipv4_address: "172.25.0.5"

    # TARGETS CONFIGURATION
    # TODO: An idea is to use other containers as targets, avoiding the use of the rPi
    # TODO: Can I run multiple instances of this "Target" container at once?
    # target:
    #     container_name: "mirai_target"
    #     dockerfile: ./Dockerfile-TRGT

    # TEST CONFIGURATION
    test:
        container_name: "mirai_test"
        hostname: test
        domainname: mirai.com
        build:
            context: .
            dockerfile: ./Dockerfile-TEST
        links:
            - cnc
        volumes:
            - /srv/docker/bind:/data/test
        networks:
            - vpcbr
            # vpcbr:
            #     ipv4_address: 172.25.0.69

    bind:
        container_name: "mirai_dns"
        hostname: test
        domainname: mirai.com
        build:
            context: .
            dockerfile: ./Dockerfile-TEST
        links:
            - cnc
        volumes:
            - /srv/docker/bind:/data/dns
        networks:
            vpcbr:
                ipv4_address: 172.25.0.69

networks:
    vpcbr:
        driver: bridge
        ipam:
            config:
                - subnet: 172.25.0.0/24
                  gateway: 172.25.0.1
